name: Breaking Change Check

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - 'FFXIVClientStructs/**/*.cs'

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: main
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr
      - name: Build Main branch
        run: dotnet build main/FFXIVClientStructs/FFXIVClientStructs.csproj
      - name: Build PR branch
        run: dotnet build pr/FFXIVClientStructs/FFXIVClientStructs.csproj -clp:NoSummary /p:ApiCompatValidateAssemblies=true /p:ApiCompatContractAssembly=${{ github.workspace }}/main/bin/Debug/FFXIVClientStructs.dll
